SELECT TOP (1000) [SquareMeter_Gross]
      ,[New_Column]
      ,[SquareMeter_Net]
      ,[Price]
      ,[Property_Type]
      ,[OpenArea_m2]
      ,[Number_of_Rooms]
      ,[Building_Age]
      ,[Number_of_Floors]
      ,[Heating]
      ,[Number_of_Bathrooms]
      ,[Parking]
      ,[Balcony]
      ,[Furnished]
      ,[In_The_Site]
      ,[Barter]
      ,[Ad_Date]
      ,[ILCE]
      ,[MAHALLE]
  FROM [HousePrices_Istanbul ].[dbo].[New_House_Prices]